### ISSUE TITLE
Got a query ?

### ISSUE THREAD

**Issue by sils** [hemangsk/viperdev-site#20]
should be more like if any questions arise drop us a mail, not only for queries

**Comment by hemangsk** [comment]
I think this covers both the question as well as the enquiry part

![screen shot 2016-12-26 at 6 13 18 pm](https://cloud.githubusercontent.com/assets/13018570/21482224/0cc0219e-cb97-11e6-814c-40b48f422415.png)

**Comment by sils** [comment]
:+1:
